import { Inter } from "next/font/google";
import "./globals.css";
import Navbar2 from "./components/navbar2";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FLYXTO | Make Things Easier.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar2 />
        {/* <Navbar/> */}
        {children}
      </body>
    </html>
  );
}
