import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Navbar2 from "./components/navbar2";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar/> */}
        <Navbar2/>
        {children}</body>
    </html>
  );
}
